language: ruby

notifications:
  email:
    - kill-bill-commits@googlegroups.com

rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-20mode
  - jruby-head

jdk:
  - openjdk7
  - oraclejdk7

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

#force travis to use only 'bundle install' instead of 'bundle install --deployments'
bundler_args: ''
